-- 001_schema.sql
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;


CREATE TABLE IF NOT EXISTS constellations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  type ENUM('ZODIAC','BRONZE','SILVER','GOLD','OTHER') NOT NULL DEFAULT 'OTHER',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
