-- MySQL Script generated by MySQL Workbench
-- Thu Oct 23 15:48:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema toptop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `toptop` ;

-- -----------------------------------------------------
-- Schema toptop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `toptop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `toptop` ;

-- -----------------------------------------------------
-- Table `toptop`.`constellations`
-- ----------------------------------------------------- 

CREATE TABLE IF NOT EXISTS `toptop`.`constellations` (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  type ENUM('ZODIAC','BRONZE','SILVER','GOLD','OTHER') NOT NULL DEFAULT 'OTHER',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `toptop`.`user`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `toptop`.`user` ;

CREATE TABLE IF NOT EXISTS `toptop`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NULL,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `toptop`.`director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toptop`.`director` ;

CREATE TABLE IF NOT EXISTS `toptop`.`director` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `toptop`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toptop`.`genre` ;

CREATE TABLE IF NOT EXISTS `toptop`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `toptop`.`production_studio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toptop`.`production_studio` ;

CREATE TABLE IF NOT EXISTS `toptop`.`production_studio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `toptop`.`broadcaster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toptop`.`broadcaster` ;

CREATE TABLE IF NOT EXISTS `toptop`.`broadcaster` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `created_by`));


-- -----------------------------------------------------
-- Table `toptop`.`producer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toptop`.`producer` ;

CREATE TABLE IF NOT EXISTS `toptop`.`producer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `toptop`.`series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toptop`.`series` ;

CREATE TABLE IF NOT EXISTS `toptop`.`series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `name` VARCHAR(255) NOT NULL,
  `release_date` DATETIME NOT NULL,
  `director_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  `release_start_date` DATETIME NULL,
  `release_end_date` DATETIME NULL,
  `production_studio_id` INT NOT NULL,
  `broadcaster_id` INT NOT NULL,
  `producer_id` INT NOT NULL,
  `type` ENUM("TV", "OVA", "ONA", "MOVIE") NULL DEFAULT 'TV',
  PRIMARY KEY (`id`, `created_by`, `director_id`, `genre_id`, `production_studio_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `toptop`.`animation_director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toptop`.`animation_director` ;

CREATE TABLE IF NOT EXISTS `toptop`.`animation_director` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `toptop`.`script`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toptop`.`script` ;

CREATE TABLE IF NOT EXISTS `toptop`.`script` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `toptop`.`storyboard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toptop`.`storyboard` ;

CREATE TABLE IF NOT EXISTS `toptop`.`storyboard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `toptop`.`episode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toptop`.`episode` ;

CREATE TABLE IF NOT EXISTS `toptop`.`episode` (
  `id` INT NOT NULL,
  `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `animation_director_id` INT NOT NULL,
  `series_id` INT NOT NULL,
  `broadcasted_date` DATETIME NULL,
  `script_id` INT NOT NULL,
  `storyboard_id` INT NOT NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
